spring:
  application:
  name: ecommerceapp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
server:
  port: 8090

