version: '3.8'


services:

app:

image: back

build:

context: .

dockerfile: Dockerfile

ports:

- "8080:8080"

environment:

SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}

SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}

SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

depends_on:

- db


db:

image: postgres:15-alpine

environment:

POSTGRES_DB: ${POSTGRES_DB}

POSTGRES_USER: ${POSTGRES_USER}

POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

ports:

- "5432:5432"

volumes:

- postgres-data:/var/lib/postgresql/data


sonarqube:

container_name: sonarqube

image: sonarqube

ports:

- "9000:9000"

volumes:

- ./sonarqube:/opt/sonarqube/data

depends_on:

- db


volumes:

postgres-data: